name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: |
            ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}

      - name: Set up environment variables
        run: |
          mkdir -p /home/ec2-user/stratostruct_server
          touch /home/ec2-user/stratostruct_server/.env
          echo "PORT=${{ secrets.PORT }}" >> /home/ec2-user/stratostruct_server/.env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> /home/ec2-user/stratostruct_server/.env
          echo "SECRET=${{ secrets.SECRET }}" >> /home/ec2-user/stratostruct_server/.env
          echo "MAPBOX_API_KEY=${{ secrets.MAPBOX_API_KEY }}" >> /home/ec2-user/stratostruct_server/.env

      - name: Deploy to EC2 instance
        run: |
          ssh -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/stratostruct_server && git pull && npm ci && pm2 restart backend && pm2 save"
        