name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}

      - name: Download or update repository
        run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }} "cd ./stratostruct_server && git pull"

      - name: Set up environment variables
        run: |
          echo 'PORT=${{ secrets.PORT }}' >> ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/stratostruct_server/.env
          echo 'MONGO_URI=${{ secrets.MONGO_URI }}' >> ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/stratostruct_server/.env
          echo 'SECRET=${{ secrets.SECRET }}' >> ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/stratostruct_server/.env
          echo 'MAPBOX_API_KEY=${{ secrets.MAPBOX_API_KEY }}' >> ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/stratostruct_server/.env

      - name: Deploy to EC2 instance
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }} "cd ./stratostruct_server && npm ci && npm start"

